scraping/scrap/urls.py
from django.urls import path
from .views import content, detail
app_name = "scrap"
urlpatterns = [
    path('content', content, name='content' ),
    path('detail/<path:qs>/', detail, name='detail')
]

scraping/scraping/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('scrap/', include('scrap.urls'))
]

scraping/scrap/models.py
from django.db import models

# Create your models here.

scraping/scrap/views.py
from django.shortcuts import render
import certifi
from django.http import JsonResponse
from bs4 import BeautifulSoup
import requests as r
import json
def content(request):
    response = r.get("https://hprera.nic.in/PublicDashboard/GetFilteredProjectsPV?DistrictList%5B0%5D.Selected=false&DistrictList%5B0%5D.Value=18&DistrictList%5B1%5D.Selected=false&DistrictList%5B1%5D.Value=24&DistrictList%5B2%5D.Selected=false&DistrictList%5B2%5D.Value=20&DistrictList%5B3%5D.Selected=false&DistrictList%5B3%5D.Value=23&DistrictList%5B4%5D.Selected=false&DistrictList%5B4%5D.Value=25&DistrictList%5B5%5D.Selected=false&DistrictList%5B5%5D.Value=22&DistrictList%5B6%5D.Selected=false&DistrictList%5B6%5D.Value=26&DistrictList%5B7%5D.Selected=false&DistrictList%5B7%5D.Value=21&DistrictList%5B8%5D.Selected=false&DistrictList%5B8%5D.Value=15&DistrictList%5B9%5D.Selected=false&DistrictList%5B9%5D.Value=17&DistrictList%5B10%5D.Selected=false&DistrictList%5B10%5D.Value=16&DistrictList%5B11%5D.Selected=false&DistrictList%5B11%5D.Value=19&PlottedTypeList%5B0%5D.Selected=false&PlottedTypeList%5B0%5D.Value=P&PlottedTypeList%5B1%5D.Selected=false&PlottedTypeList%5B1%5D.Value=F&PlottedTypeList%5B2%5D.Selected=false&PlottedTypeList%5B2%5D.Value=M&ResidentialTypeList%5B0%5D.Selected=false&ResidentialTypeList%5B0%5D.Value=R&ResidentialTypeList%5B1%5D.Selected=false&ResidentialTypeList%5B1%5D.Value=C&ResidentialTypeList%5B2%5D.Selected=false&ResidentialTypeList%5B2%5D.Value=M&AreaFrom=&AreaUpto=&SearchText=", verify=False) 
    soup = BeautifulSoup(response.content, 'html.parser')
    data = soup.select('div[class="col-lg-6"]')[:6]
    details = list()
    for i in data:
         project_name = i.find('span', class_='font-lg fw-600').text
         rera_number = i.find('a').text
         project_type = i.find_all('span')[1].text.strip() 
         phone_number = i.find('i', class_='fa-mobile-alt').find_next('span').text.strip()
         email = i.find('i', class_='fa-at').find_next('span').text.strip()
         address = i.find('i', class_='fa-map-marker-alt').find_next('span').text.strip()
         valid_upto = i.find('div', class_='text-right font-xxs').find('span', class_='text-orange').text.strip()
         data_qs = i.find('a')['data-qs']
         details.append({
             'project_name': project_name,
             'rera_no': rera_number,
             'project_type': project_type,
             'phone_no':phone_number,
             'email': email,
             'address':address,
             'valid_upto': valid_upto,
             'qs': data_qs
         })

    return render(request, 'contents/content.html', {'details':details}) 


def detail(request, qs):
    response = r.get(f"https://hprera.nic.in/Project/ProjectRegistration/PromotorDetails_PreviewPV?qs={qs}", verify=False)
    soup = BeautifulSoup(response.content, 'html.parser')
    name = soup.find('td', text='Name').find_next_sibling('td').text.strip()
    pan_no = soup.find('td', text='PAN No.').find_next_sibling('td').text.strip()
    gstin_no = soup.find('td', text='GSTIN No.').find_next_sibling('td').find('span').text.strip()
    permanent_address = soup.find('td', text='Permanent Address').find_next_sibling('td').text.strip()
    return render(request, 'contents/detailview.html', {'name':name, 'pan_no':pan_no, 'gstin_no': gstin_no, 'address':permanent_address})

# https://hprera.nic.in/Project/ProjectRegistration/PromotorDetails_PreviewPV?qs=

scraping/scraping/views.py
from django.shortcuts import render

def home(requests):
    return render(requests, 'home.html')

scraping/scrap/templates/contents/content.html
{% extends "layout.html" %}

{% block title %}Content{% endblock title %}

{% block content %}
<div class="flex justify-center mt-[100px] mb-[100px]">
    <div class="grid grid-rows-2 grid-cols-2 gap-2 ">
        {% for i in details %}
<div class="block max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">

    <div class="text-[20px]">{{i.project_name}}</div>
    <div class="font-semibold">
        <a href="{% url 'scrap:detail' i.qs|urlencode %}">{{ i.rera_no }}</a>
    </div>
    <div>{{i.project_type}}</div>
    <div>{{i.phone_no}}</div>
    <div>{{i.email}}</div>
    <div>{{i.address}}</div>
    <div>{{i.valid_upto}}</div>
    
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

scraping/scrap/templates/contents/detailview.html
{% extends "layout.html" %}


{% block title %}Detailview{% endblock title %}

{% block content %}
        



<div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-6 py-3">
                    Name
                </th>
                <th scope="col" class="px-6 py-3">
                    PAN No
                </th>
                <th scope="col" class="px-6 py-3">
                    GSTIN No
                </th>
                <th scope="col" class="px-6 py-3">
                    Permanent Address
                </th>
            </tr>
        </thead>
        <tbody>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                    {{name}}
                </th>
                <td class="px-6 py-4">
                    {{pan_no}}
                </td>
                <td class="px-6 py-4">
                    {% if gstin_no %}
                    {{gstin_no}}
                    {% else %}
                    -NA-
                    {% endif %}
                 
                </td>
                <td class="px-6 py-4">
                    {{address}}
                </td>
            </tr>
           
        </tbody>
    </table>
</div>


{% endblock content %}

scraping/templates/home.html
{% extends "layout.html" %}
{% load static %}
{% block title %}
Home
{% endblock title %}

{% block content %}
<p class='font-semibold text-center text-[20px] mt-[100px]'>Please click the Task to view ...</p>
{% endblock content %}

scraping/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}Primenumber Technologies{% endblock title %}</title>
</head>
<body>
    

<nav class="bg-black border-gray-200 dark:bg-gray-900 text-white">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
      <a href="https://flowbite.com/" class="flex items-center space-x-3 rtl:space-x-reverse">
          <span class="self-center text-2xl font-semibold whitespace-nowrap text-white">Primenumber Technologies</span>
      </a>
      <div class="hidden w-full md:block md:w-auto" id="navbar-default">
           <p class='text-white font-semibold'><a href="{% url "scrap:content" %}">Task</a></p>
      </div>
    </div>
    
  </nav>
  
    {% block content %}{% endblock content %}
</body>
</html>